# Theme settings
remote_theme: fongandrew/hydeout
theme: jekyll-theme-hydeout

# Don't put these files on built website
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore
  
# Setup
title: "On the Numbers"
description: "The YouTube political community is dominated by big names like Let's Talk Elections, Red Eagle Politics, and more! But there are also countless smaller content creators who put a lot of work into what their platforms, and although we might not agree on everything, we hope that this website can serve as a place to not only get up-to-date information about the state of American politics, but also a forum to find new creators and channels to watch as well as interact and educate yourself on our rich history and political system as the 2020 elections draw near. Thanks to everyone for being here!"
url: https://onthenumbers.github.io
baseurl: "/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
      
paginate: 5
    
permalink:        /:year/:month/:day/:title.html
sidebar_home_link: true # this is the sidebar VERY IMPORTANT
