# Dependencies
#markdown:         kramdown
highlighter:      rouge

# Setup
title:            On the Numbers
tagline:          ''
description:      'The YouTube political community is dominated by big names like Let's Talk Elections, Red Eagle Politics, and more! But there are also countless smaller content creators who put a lot of work into what their platforms, and although we might not agree on everything, we hope that this website can serve as a place to not only get up-to-date information about the state of American politics, but also a forum to find new creators and channels to watch as well as interact and educate yourself on our rich history and political system as the 2020 elections draw near. Thanks to everyone for being here!'
url:              https://onthenumbers.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Ethan Eblaghie'
  url:            https://www.youtube.com/channel/UCV9leRwTyIBwE-mZ4EI7FDw

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      onthenumbers

# google_analytics: UA-100461102-1

# Theme settings
remote_theme: fongandrew/hydeout
theme: jekyll-theme-hydeout
